### ISSUE TITLE
Upgrading from falcon will destroy current install if fails

### ISSUE THREAD

**Issue by DBezemer** [kaltura/installer#11]
```
Creating plugins dynamic enumerations
Failed to create plugins dynamic enumerations
Do you want to cleanup? (y/N)
> y
```
will leave you with only the web directory, a warning at the start of the process would be appropriate, or better even: a backup mechanism in the upgrade routine (dump db's tar.gz the data directories) possibly with the option to automatically recover to falcon

**Comment by Jhankal** [comment]
Creating plugins dynamic enumerations
Failed to create plugins dynamic enumerations
Do you want to cleanup? (y/N)
> y

**Comment by jessp01** [comment]
Hello,

This repo is deprecated. To install, please use https://github.com/kaltura/platform-install-packages/ which has the latest versions and supports RHEL/CentOS 6,7 and Debian/Ubuntu.
